name: Firebase deploy
on:
 push:
  branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Setup Node.js enviroment
      uses: actions/setup-node@master
      with:
        node-version: 14
    
    - name: Check the code
      working-directory: ./functions
      run: |
       npm ci
       npm run lint:fix
       npm run build

    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy
      env:
        FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}