name: Node.js CI

on:
 pull_request:
  branches: [main]


jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js enviroment
      uses: actions/setup-node@master
      with:
        node-version: '14'